#:kivy 1.0.9
<Card>:
	size: 80, 140
	canvas:
		Rectangle:
			pos:self.pos
			size:self.size
<CardGame>:
	canvas:
		Rectangle:
			pos: 0, self.center_y
			size: self.width, 2

		Rectangle:
			pos: self.width - 1.2*self.width/8, self.height/2 + 1.2*self.height/4 - self.height/4
			size: self.width/8, self.height/4

		Rectangle:
			pos: self.width - 1.2*self.width/8, self.height/2 - 1.2*self.height/4
			size: self.width/8, self.height/4